### ISSUE TITLE
Doesn't compile with Xcode 6 and iOS 8

### ISSUE THREAD

**Issue by alex-hudenko** [jharwig/PPSSignatureView#9]
![screen shot 2014-06-06 at 3 27 19 pm](https://cloud.githubusercontent.com/assets/231547/3200613/7c27a2d6-ed7e-11e3-9b9e-f629c07eb53e.png)

**Comment by sridvijay** [comment]
Hey,
I had the same problem, but I was able to fix it by adding an additional import statement referring to a file in the OpenGLES framework. Pull request sent, but in the meanwhile here it is: 84dd191
Good Luck!

**Comment by kyfxbl** [comment]
@sridvijay 

hi, it works, thanks. but then there's another error message:
Undefined symbols for architecture arm64

didn't you meet this problem?
